### ISSUE TITLE
Question: Why not Vectors?

### ISSUE THREAD

**Issue by FrankC01** [usethesource/capsule#18]
With a full grok of capsule attained, kudos again, I'm wondering why not Vectors (as in Clojure vectors)?

Does the sequential nature diminish the space/performance advantage of Trie?

Curious but not critical.

**Comment by msteindorfer** [comment]
Hi Frank, vectors will be added in the future. 

There's no technical reason or limitation (I'm well acquainted with literature on persistent vectors), I just didn't allocate the time yet to properly engineer a performant vector data type.

The optimizations of sets/maps and vectors are different, because the former are sparse data structures whereas the latter are typically implemented as dense data structures.

**Comment by FrankC01** [comment]
Thanks, as I am using Clojure's Vector and capsule's Map and Set as references for a non-java runtime implementation I'm set for the moment. If I venture into moving my Vector I will let you know of any observations I may have.
